version: "3.1"
services:
        minecraft:
                image: customminecraft
                volumes:
                        - ../minecraftconfig:/opt/minecraft/
                container_name: minecraft
                ports:
                        - "25565:25565"
                        - "8080:8080"
        jellyfin:
                image: jellyfin/jellyfin:10.3.5
                restart: always
                volumes:
                        - /external/Anime:/media/Anime:ro
                        - /external/Movies:/media/Movies:ro
                        - /external/TV:/media/TV:ro
                        - /external/Training:/media/Training:ro
                        - /external/Documentaries:/media/Documentaries:ro
                        - /external/Music:/media/Music:ro
                        - ../jellyfin/config:/config
                        - ../jellyfin/cache:/cache
                container_name: jellyfin
                network_mode: "host"
        sonarr:
                container_name: sonarr
                image: linuxserver/sonarr
                restart: always
                volumes:
                        - /external/Downloads:/data
                        - ../sonarr:/config
                        - /external/TV:/tv
                        - /external/Anime:/anime
                ports:
                        - "8989:8989"
                environment:
                        - PUID=0
                        - GUID=0
        seedbox:
                container_name: seedbox
                cap_add:
                        - NET_ADMIN
                image: haugene/transmission-openvpn
                volumes:
                        - /external/Downloads:/data
                        - ../transmission:/config
                        - /etc/localtime:/etc/localtime:ro
                environment:
                        - CREATE_TUN_DEVICE=true
                        - OPENVPN_PROVIDER=PIA
                        - OPENVPN_CONFIG=US\ Chicago
                        - LOCAL_NETWORK=192.168.0.0/16
                        - TRANSMISSION_WEB_UI=transmission-web-control
                ports:
                        - 9091:9091
                env_file:
                        - seedbox.env
        jackett:
               container_name: jackett
               image: linuxserver/jackett
               volumes:
                       - ../jackett/config
                       - /etc/localtime:/etc/localtime:ro
                       - /external/Downloads:/downloads
               ports:
                       - "9117:9117"
               restart: always
        mysql:
                container_name: mysql
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: default
                image: mysql
        tt-rss:
                image: linuxserver/tt-rss
                container_name: tt-rss
                ports:
                       - "8081:80"
                restart: always
                volumes:
                       - /etc/localtime:/etc/localtime:ro
                       - ../tt-rss:/config
                environment:
                       - PUID=101
                       - GUID=102
        radarr:
                image: linuxserver/radarr
                container_name: radarr
                environment:
                        - PUID=101
                        - GUID=102
                volumes:
                        - ../radarr:/config
                        - /external/Movies:/movies
                        - /external/Downloads:/data
                        - /etc/localtime:/etc/localtime:ro
                ports:
                        - "7878:7878"
                labels:
                        - "traefik.frontend.rule=Host:radarr.yggdrasil.attlocal.net"
                        - "traefik.enable=true"
                        - "traefik.port=7878"
                        - "traefik.backend=radarr"
                restart: always
        bazarr:
                image: linuxserver/bazarr
                container_name: bazarr
                environment:
                        - PUID=0
                        - GUID=0
                ports:
                        - "6767:6767"
                restart: always
                volumes:
                        - ../bazarr:/config
                        - /external/Movies:/movies
                        - /external/TV:/tv
                        - /external/Anime:/anime
        novpn-seedbox:
                image: linuxserver/transmission
                container_name: novpn-seedbox
                environment:
                        - PUID=0
                        - GUID=0
                volumes:
                        - ../transmission:/config
                        - /external/PublicDownloads:/downloads
                ports:
                        - "9092:9091"
                        - "51414:51413"
        nginx:
                image: nginx
                container_name: nginx
                volumes:
                        - /external/.secret:/usr/share/nginx/html:ro
                restart: always
                ports:
                        - "7776:80"
