version: '3'
services:
        reverse-proxy:
                restart: always
                command:
                image: traefik:alpine
                command: --api --docker
                container_name: traefik
                ports:
                        - "80:80"
                        - "8080:8080"
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ./traefik:/etc/traefik
