version: '3'
services:
        minecraft:
                image: itzg/minecraft-server
                restart: always
                command: "--noconsole"
                volumes:
                        - ../minecraft:/data
                environment:
                        - TYPE=SPIGOT
                        - EULA=TRUE
                container_name: minecraft          
